export const ASYNC_START = 'ASYNC_START'
export const ASYNC_END = 'ASYNC_END'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const UPDATE_AUTH_FIELD = 'UPDATE_AUTH_FIELD'
export const REDIRECT = 'REDIRECT'
export const APP_LOAD = 'APP_LOAD'

export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED'
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED'

export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD'