export const ASYNC_START = 'ASYNC_START'
export const ASYNC_END = 'ASYNC_END'

export const REDIRECT = 'REDIRECT'
export const APP_LOAD = 'APP_LOAD'

export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD'
export const ADD_SEARCH_FEATURE = 'ADD_SEARCH_FEATURE'
export const REMOVE_SEARCH_FEATURE = 'REMOVE_SEARCH_FEATURE'

export const SET_MAP_POSITION = 'SET_MAP_POSITION'